# Generated by Django 2.1.7 on 2019-04-27 01:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190119_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
