# Generated by Django 2.1.7 on 2019-08-19 21:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
