# Generated by Django 3.0.3 on 2020-03-03 21:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190819_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invoices',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
