# Generated by Django 3.0.3 on 2020-11-27 20:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
