# Generated by Django 3.0.3 on 2021-05-18 03:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201127_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
