# Generated by Django 2.1.7 on 2019-08-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
