# Generated by Django 3.0.3 on 2020-10-02 00:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircraft_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='model',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
