# Generated by Django 3.0.3 on 2020-11-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20201121_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=25)),
                ('name', models.TextField()),
            ],
        ),
    ]
