# Generated by Django 3.0.3 on 2020-11-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notifytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifytype',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notifytype',
            name='title',
            field=models.CharField(default='On Event Scheduled', max_length=256),
            preserve_default=False,
        ),
    ]
